# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 28 Nov 2009 17:47:26 -0500
*	@ALL	1
*	@teacher	8
*	@students	1
dokuwiki	@ALL	0
start	@teacher	2
start	@director	2
wikiadmin:*	@teacher	1
wikiadmin:*	@ALL	0
wikiadmin:*	@director	8
