# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 28 Nov 2009 17:47:26 -0500
*	@ALL	1
*	@teacher	2
*	@students	1
dokuwiki	@ALL	0
start	@teacher	2
start	@director	2
uav:*	@teacher	8
uav:*	@director	8
wiki:*	@students	1
wiki:*	@director	8
wiki:*	@teacher	2
wiki:acknowledgements	@ALL	1
wiki:exercise_weld	@students	2
wiki:grass_rs_gui	@students	2
wiki:personalpages:*	@teacher	2
wiki:personalpages:*	@students	2
wiki:personalpages:albamininni	@students	2
wiki:personalpages:albamininni	@teacher	2
wiki:python:*	@teacher	2
wiki:python:pythonhome	@teacher	2
wiki:rasdaman:*	@teacher	8
wiki:students	@ALL	0
wiki:students	@teacher	2
wiki:time_series	@students	2
wiki:upcoming	@teacher	2
wiki:upcoming	@ALL	2
wiki:weld_hdf	@students	2
wikiadmin:*	@teacher	1
wikiadmin:*	@ALL	0
wikiadmin:*	@director	8
wikibas10:*	@director	8
wikidk:*	@director	8
wikiholland:*	@director	8
wikiqgis:*	@director	8
wikistud:*	@ALL	1
wikistud:*	@teacher	1
wikistud:*	@students	1
wikistud:*	@director	8
wikistud:holland2013	@ALL	0
wikistud:holland2013	@students	1
wikistud:holland2013	@teacher	2
wikistudholland:*	@students	8
wikistudholland:*	@director	8
wikitz:*	@director	8
wiki:reglistmatera17	@students	2
wikistud:matera2017proj	@students	2
wikistud:mat2017_perroneantonio	@students	2
wikistud:mat2017_annahamps	@students	2
wikistud:mat2017_jakobhagenauer	@students	2
wikistud:mat2017_juanherrera	@students	2
wikistud:mat2017_marcogirardello	@students	2
wikistud:mat2017_mariannestoesel	@students	2
wikistud:mat2017_patrick_shwager	@students	2
wikistud:mat2017_thomaskandler	@students	2
wikistud:mat2017_tinazivec	@students	2
