<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: new_ost4sem_admin
 * Date: Fri, 15 Apr 2016 05:17:16 -0400
 */

$conf['title'] = '';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['target']['extern'] = 'blanc';
$conf['sitemap'] = 1;
$conf['compress'] = 0;
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['googlecal']['gcal_js_ok'] = 1;
$conf['tpl']['monobook']['mb_navigation_location'] = ':wiki:start';
$conf['tpl']['monobook']['mb_hbc_loc'] = 'bottom';

// end auto-generated content
